### ISSUE TITLE
Data check in frontend before they are sent to backend

### ISSUE THREAD

**Issue by Vincmza** [Fabou291/WLM#9]
- [x] Password inputs checked while user is registering, if ok data are sent to backend
- [x] Password schema to determine (how hard, how long and what it is supposed to contain)
- [x] Email input check ? Regex that doesn't allow specific characters to avoid code injection ?

**Comment by FabriceGaillard** [comment]
About password rules when registering : 
I use this regex into back side : /^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)(?=.*\W)[a-zA-Z\d\W]{12,}$/
It check if it have : 1 minuscule, 1 majuscule, 1 number, 1 alphabetic, 1 special character. The password must contain at least 12 characters.
An other thing about this : A second field is checked, named passwordConfirmation. It allows to check if password is not accidental.
Same, to update password.
The limit of the password field is set to 180 character into database

NB : You could use some packages to check validity of password or email
